spring:
  # ===============================
  # Activation Postgresql
  # ===============================
  config:
    activate:
      on-profile: postgresql

  # ===============================
  # Database
  # ===============================
  datasource:
    driverClassName: org.postgresql.Driver
    url: url
    username: username
    password: password

  # ===============================
  # Database version Management
  # ===============================
  flyway:
    locations: classpath:db/migration/postgresql

  # ===============================
  # Spring Data Jpa
  # ===============================
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
