spring:
  # ===============================
  # Activation Oracle or Postgresql
  # ===============================
  config:
    activate:
      on-profile: oracle

  # ===============================
  # Database
  # ===============================
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: url
    username: username
    password: password

  # ===============================
  # Spring Data Jpa
  # ===============================
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
