# If the code you are adding is new and does not belong to any existing section below,
# please add it at the bottom of this file.

server:
  port: 0
  # ===============================
  # Grafana metric
  # ===============================
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  # ===============================
  # Feign client
  # ===============================
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

  # ===============================
  # Database version Management
  # ===============================
  flyway:
    enabled: false
    baseline-on-migrate: true

  data:
    # ===============================
    # pagination
    # ===============================
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

    # ===============================
    # Redis
    # ===============================
    redis:
      host: host
      port: port
      password: password

  # ===============================
  # cross-schema 참조 동작을 위해 Hibernate 가 테이블명을 그대로 사용하도록 지정
  # ===============================
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: false

  # ===============================
  # File size limit
  # ===============================
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

# ===============================
# Eureka client
# ===============================
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

# ===============================
# Management
# ===============================
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /gate/actuator
      exposure:
        include: refresh, health, info, prometheus

# ===============================
# Docs
# ===============================
springdoc:
  api-docs:
    path: /gate/v3/api-docs

# ===============================
# Gateway URL
# ===============================
gateway:
  url: ${gateway.url, http://localhost:8080}

# ===============================
# Gateway Demo URL
# ===============================
gate:
  demo:
    url: https://develop.univs.ai:7650/m/test

# ===============================
# File upload option
# ===============================
file:
  enable:
    upload: true
  api-endpoint:
    get: ${file.api-endpoint.get, /api/v1/file}
  root-path: filepath
  secret-key: secretkey
  algorithm:
    way: way
    mod: mod

# ===============================
# JWT
# ===============================
jwt:
  secret: ${JWT_SECRET:357638792F423F4428472B4B6250655368566D597133743677397A2443264629}
  create-user-token-expiry: 300000

# ===============================
# API KEY
# ===============================
api-key:
  prefix: gate_
  length: 31
  expiry-days: 3600

# ===============================
# Redis channel
# ===============================
redis:
  demo:
    channel: demo:result

logging:
  level:
    ai.univs.gate.shared.locale: DEBUG