# If the code you are adding is new and does not belong to any existing section below,
# please add it at the bottom of this file.

server:
  port: 0
  # ===============================
  # Grafana metric
  # ===============================
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  # ===============================
  # Feign client
  # ===============================
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

  # ===============================
  # Java 21 Virtual Threads
  # ===============================
  threads:
    virtual:
      enabled: true

  # ===============================
  # Redis
  # ===============================
  data:
    redis:
      host: host
      port: port
      password: password

# ===============================
# Eureka client
# ===============================
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

# ===============================
# Management
# ===============================
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /notify/actuator
      exposure:
        include: refresh, health, info, prometheus

# ===============================
# JWT
# ===============================
jwt:
  secret: ${JWT_SECRET:357638792F423F4428472B4B6250655368566D597133743677397A2443264629}

# ===============================
# Socket connection info
# ===============================
web:
  socket:
    allow:
      origins: https://develop.univs.ai:18090

# ===============================
# Socket subscriber info
# ===============================
notify:
  subscriptions:
    - channel: demo:result
      routing-key: transactionUuid
      topic-prefix: /topic/demo
    - channel: plan:notify
      routing-key: accountId
      topic-prefix: /topic/plan

# ===============================
# Socket logging
# ===============================
logging:
  level:
    # Spring의 WebSocket 전반에 대한 로그 (연결, 핸드셰이크 등)
    org.springframework.web.socket: TRACE
    # STOMP 등 메시징 프로토콜 처리 관련 로그 (메시지 구독, 발행, 브로커 등)
    org.springframework.messaging: TRACE
    # (선택) 내장된 Tomcat을 사용하는 경우, 더 낮은 수준의 WebSocket 통신 로그
    org.apache.tomcat.websocket: DEBUG