# If the code you are adding is new and does not belong to any existing section below,
# please add it at the bottom of this file.

server:
  port: 0
  # ===============================
  # Grafana metric
  # ===============================
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  # ===============================
  # Kafka
  # ===============================
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-batch-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # ===============================
  # Feign client
  # ===============================
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

# ===============================
# Eureka client
# ===============================
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: notification-socket-service
    preferIpAddress: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

# ===============================
# Management
# ===============================
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /notification-socket/actuator
      exposure:
        include: refresh, health, info, prometheus

# ===============================
# Socket connection info
# ===============================
websocket:
  config:
    connect:
      url: /ws/notification
    broker:
      pub-destination: /ws/app
      sub-destination: /ws/notification/topic

# ===============================
# Kafka topic
# groupId : <'service name'>-consumer[-'environment']
# topic   : serviceName.method.env
# ===============================
app:
  kafka:
    noti:
      common:
        group-id: stag-notification-group
      topics:
        comp:
          updated: comp.updated.stag
        application:
          created: application.created.stag
          updated: application.updated.stag
        service-key:
          created: service-key.created.stag
          updated: service-key.updated.stag
          deleted: service-key.deleted.stag
      batch:
        topics: stag-notification-batch
        group-id: stag-notification-batch-group
      device:
        topics: stag-notification-device
        group-id: stag-notification-device-group