# chore: 자동배포 파이프라인 테스트

spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://config-server:8888

---

server.port: 8761

spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
