spring:
  config:
    activate:
      on-profile: oracle

  datasource:
    driverClassName: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
