-- descriptor_type, descriptor_body 필드 추가, descriptor 설명 수정
ALTER TABLE UNIVS."DESCRIPTOR" ADD DESCRIPTOR_TYPE RAW(8) NULL;

COMMENT ON COLUMN UNIVS."DESCRIPTOR".DESCRIPTOR_TYPE IS '특징점 타입';

ALTER TABLE UNIVS."DESCRIPTOR" ADD DESCRIPTOR_BODY RAW(512) NULL;

COMMENT ON COLUMN UNIVS."DESCRIPTOR".DESCRIPTOR_BODY IS '특징점';

COMMENT ON COLUMN UNIVS."DESCRIPTOR"."DESCRIPTOR" IS '추출된 레거시 특징점';

-- 기존에 등록된 사용자 특징점 분리 업데이트
UPDATE UNIVS.DESCRIPTOR SET descriptor_type = HEXTORAW(SUBSTR(RAWTOHEX(descriptor), 1, 16)), descriptor_body = HEXTORAW(SUBSTR(RAWTOHEX(descriptor), 17, 1024));

-- descriptor_type, descriptor_body NOT NULL
ALTER TABLE UNIVS."DESCRIPTOR" MODIFY DESCRIPTOR_TYPE RAW(8) NOT NULL;

ALTER TABLE UNIVS."DESCRIPTOR" MODIFY DESCRIPTOR_BODY RAW(512) NOT NULL;
