ALTER TABLE UNIVS.BRANCH DROP COLUMN created_by;
ALTER TABLE UNIVS.BRANCH DROP COLUMN modified_by;

ALTER TABLE UNIVS."DESCRIPTOR" DROP COLUMN created_by;
ALTER TABLE UNIVS."DESCRIPTOR" DROP COLUMN modified_by;
