-- UG-296: UNIVS. 스키마 프리픽스 제거. 사유는 V2 주석 참고.
ALTER TABLE BRANCH DROP COLUMN created_by;
ALTER TABLE BRANCH DROP COLUMN modified_by;

ALTER TABLE "DESCRIPTOR" DROP COLUMN created_by;
ALTER TABLE "DESCRIPTOR" DROP COLUMN modified_by;
