server.port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/univs-dcun/gate.git
          default-label: master
          search-paths: config-repo
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
        native:
          search-locations: file:///config-repo

# true: 안전하게 종료, prometheus: actuator 에서 허용할 api (ex./actuator/prometheus)
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

# tomcat metric 설정 (그라파나에서 Jetty metric(default) 대신 tomcat 을 보기 위함
server:
  tomcat:
    mbeanregistry:
      enabled: true