server.port: 8888

# chore: 자동배포 파이프라인 테스트

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 별도 config 저장소 (main 브랜치가 dev/stage/prod 전 환경의 단일 진실) (UG-233)
          uri: https://github.com/univs-dcun/gate-config.git
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
        native:
          search-locations: file:///config-repo

# true: 안전하게 종료, prometheus: actuator 에서 허용할 api (ex./actuator/prometheus)
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

# tomcat metric 설정 (그라파나에서 Jetty metric(default) 대신 tomcat 을 보기 위함
server:
  tomcat:
    mbeanregistry:
      enabled: true

# ===============================
# Logging
# ===============================
logging:
  level:
    org.springframework.cloud.config.server: DEBUG