spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.135:5432/auth
    username: postgres
    password: univs0411!
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
